### PR TITLE
Revert "Fixes for circular dependencies preventing Entity destruction, and Listener re/un-assignment"

### PR DESCRIPTION
**Pull request by thijsmie**
Reverts eclipse-cyclonedds/cyclonedds-python#129

### CODE REVIEW

**Comment by thijsmie** [comment]
@willstott101 if I simply revert this PR then we also lose the Listener updates...

**Comment by willstott101** [comment]
Oh they all squashed :( I'll open a PR 1 sec

**Comment by willstott101** [comment]
See: #133

**Comment by thijsmie** [comment]
9k, closing this.

**Pull request closed without merging**
