### PR TITLE
Coverage inside Azure Pipelines

### PR DESCRIPTION
**Pull request by thijsmie**
This pull request switches from codecov to coverage inside Azure Pipelines. An example run can be seen [here](https://dev.azure.com/tmiedema/cyclonedds-python/_build/results?buildId=313&view=codecoverage-tab).

### CODE REVIEW

**Review by k0ekk0ek — APPROVED** [review]
I like it :+1: Coverage per run is great. Could we do something like having the build fail if coverage drops?

**Comment by thijsmie** [comment]
I think [this](https://marketplace.visualstudio.com/items?itemName=mspremier.BuildQualityChecks) would work for that. Of course it would also be possible to fail the CI based on a fixed threshold from inside the pipeline.

**Review by eboasson — APPROVED** [review]

**Comment by eboasson** [comment]
I wonder what's up with the ECA check ...

**Comment by k0ekk0ek** [comment]
Eclipse had an outage yesterday, I hit revalidate and it's green now. Merging.

**Pull request merged**
