### PR TITLE
Document that Python headers are required

### PR DESCRIPTION
**Pull request by alknemeyer**
Addresses issue #119

### CODE REVIEW

**Review by thijsmie — APPROVED** [review]

**Comment by thijsmie** [comment]
Even for small contributions the Eclipse Committers agreement, see [the eclipse wiki](https://wiki.eclipse.org/Development_Resources/Contributing_via_Git), is required to be signed. It is to make sure you understand that you are contributing to an open source project that will forever be free and open to anyone to use and distribute. Would you be willing to go through the process of signing it? It shouldn't take more than a couple of minutes.

**Comment by alknemeyer** [comment]
I made an account and signed the ECA after committing this code.
image
Is there a second agreement I need to sign for this project, or do I just need to trigger the `eclipsefdn/eca` action again?

**Comment by thijsmie** [comment]
That should work, but also the email on the commit must match whatever you used on the eclipse website I believe. You can rewrite the commit and force push it here to make that work.

**Comment by alknemeyer** [comment]
Hi, I think this can be merged now :)

**Review by thijsmie — APPROVED** [review]

**Comment by thijsmie** [comment]
Thanks for your contribution!

**Pull request merged**
