### PR TITLE
Fix struct inheritance

### LINKED ISSUE #162: Inheritance in cyclonedds-python not working or not implemented
Independent structs and structs inheritance seem to generate the same python code. Let’s have an example.
 
Example of two different structs in an IDL file:
 
```
module module_test {
    struct struct_test_A {
        char var;
    };
    struct struct_test_B {
        char varr;
    };
};
```
 
 Example of structs inheritance in another IDL file:
 
```
module module_test {
    struct struct_test_A {
        char var;
    };
    struct struct_test_B : struct_test_A {
        char varr;
    };
};
```
 
When we (@Bit-Seq,@javiersorianoruiz) translate from IDL to Python the examples above, both give the same result:

 
```

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import module_test

@dataclass
@annotate.final
@annotate.autoid("sequential")
class struct_test_A(idl.IdlStruct, typename="module_test.struct_test_A"):
    var: types.char

@dataclass
@annotate.final
@annotate.autoid("sequential")
class struct_test_B(idl.IdlStruct, typename="module_test.struct_test_B"):
    varr: types.char
```

There seems to be a bug and the inheritance case is not implemented in Python.
Why different IDL files give the same result?

### PR DESCRIPTION
**Pull request by thijsmie**
This fixes #162 and some related issues around struct inheritance. @jordialexalar will you please test if this fixes your issue?

### CODE REVIEW

**Comment by jordialexalar** [comment]
Hi Thijs,

Thanks for your answer.
After testing the changes you made, I can say that inheritance works
properly, like for example in your file tests/test_struct_inheritance.py
<https://github.com/eclipse-cyclonedds/cyclonedds-python/pull/164/files#diff-bdd22c79cf592e46ebb88c7aabe75bc97f7eff3162a06f48bcbf764e5d05d890>
but
when we use inheritance in our examples of conexion , with file
publisher.py and subscriber.py,
another error arises.
If attached in this e-mail the files of the example and another word file
with the error that appears when the subscriber.py file is executed.
Perhaps you can help us with the problem.

Thanks for all

Jorge Alejandre

**Comment by thijsmie** [comment]
Hi @jordialexalar,

Could you send the files you mentioned here or to my email opensource _at_ tmiedema.com, attaching them to the comment email doesn't seem to have worked.

**Comment by thijsmie** [comment]
Hi @jordialexalar,

Thank you for your reproducer, it helped me track down a subtle way it could still go wrong. With this extra one-line change your example now works for me.

**Comment by jordialexalar** [comment]
Hi Thijs,

Thanks for your answer.

After testing the changes you have made, I've just tried them,and as you
say now it works fine.

Thanks for all

Jorge Alejandre

**Pull request merged**
